version: '3.8'

services:
  financial-chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financebot
    ports:
      - "8501:8501"    # Streamlit
      - "11434:11434"  # Ollama API (optional exposure)
    volumes:
      - ollama_data:/root/.ollama      # Persist downloaded models
      - ./data:/app/data                # Persist database
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

volumes:
  ollama_data:
    driver: local
